name: "PR Notification"
on:
    pull_request:
        types: [opened]

jobs:
    notify: 
        runs-on: ubuntu-latest
        steps:
            - name: Comment on PR
              uses: thollander/actions-comment-pull-request@v2.5.0
              with:
                  message: 'Thanks for submitting a PR, @thefourcraft. Will merge it soon.'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
